#!/bin/bash
echo "============================================"
echo "   VERIFICAÇÃO FINAL DO SISTEMA AI_CORE"
echo "============================================"
echo ""
echo "✅ CONFIGURAÇÃO ATUAL:"
echo "  • Memória: 8GB (realista)"
echo "  • Batch: 128 registros"  
echo "  • Cores: 4"
echo "  • API: Removida"
echo "  • Airflow: Script pronto"
echo ""
echo "📂 ARQUIVOS IMPORTANTES:"
echo -n "  • run_for_airflow.py: "
[[ -f /home/lgsilva/SAT_IA/ai_core/run_for_airflow.py ]] && echo "✅" || echo "❌"

echo -n "  • submit_treino.sh (8GB): "
grep -q "8g" /home/lgsilva/SAT_IA_API/aicore-gpu/scripts/submit_treino.sh 2>/dev/null && echo "✅" || echo "❌"

echo -n "  • global_config.py: "
[[ -f /home/lgsilva/SAT_IA/ai_core/src/ai_toolkit/config/global_config.py ]] && echo "✅" || echo "❌"

echo ""
echo "🚀 COMANDOS PARA PRODUÇÃO:"
echo ""
echo "1. TREINAR MODELO:"
echo "   cd /home/lgsilva/SAT_IA_API/aicore-gpu/scripts"
echo "   ./submit_treino.sh -i hdfs:///data/train.csv -o hdfs:///models/v2 -m modelo_v2"
echo ""
echo "2. PREDIÇÃO BATCH:"
echo "   ./submit_predicao.sh -i hdfs:///data/batch.csv -o hdfs:///output/pred.csv -m modelo_v2"
echo ""
echo "3. USO NO AIRFLOW:"
echo "   from airflow import DAG"
echo "   from airflow.operators.bash import BashOperator"
echo "   "
echo "   predict = BashOperator("
echo "       task_id='predict',"
echo "       bash_command='cd /home/lgsilva/SAT_IA/ai_core && python3 run_for_airflow.py input.csv output.csv'"
echo "   )"
echo ""
echo "============================================"
echo "✅ SISTEMA PRONTO PARA PRODUÇÃO!"
echo "============================================"
